### ISSUE TITLE
can't input value

### ISSUE THREAD

**Issue by bluelovers** [nguyenq/jTessBoxEditorFX#1]
![2018-08-20-02-49-42-1](https://user-images.githubusercontent.com/167966/44311988-c8888180-a423-11e8-8c20-cc53a6995b56.png)

**Comment by nguyenq** [comment]
The minimum size is 400 x 600.

**Comment by nguyenq** [comment]
The values are entered via the up/down arrow buttons.

**Comment by bluelovers** [comment]
why not make it allow input??

**Comment by nguyenq** [comment]
To prevent input of wildly out-of-range values. The coordinates should vary only slightly from original locations.

**Comment by bluelovers** [comment]
but it make always need click > 15, for each lol

**Comment by bluelovers** [comment]
![2018-08-20-10-04-36-2](https://user-images.githubusercontent.com/167966/44316826-83367500-a460-11e8-829b-e6ad213ca267.png)

**Comment by nguyenq** [comment]
In such cases, it might be faster to delete and insert a new box.

**Comment by nguyenq** [comment]
There are hotkeys available in Box View for ease of editing. Check the app's Help for more info.

**Comment by nguyenq** [comment]
Can this be closed?
