### ISSUE TITLE
Error: cannot find or unable to load the main class net.sourceforge.tessboxeditor.JTessBoxEditor

### ISSUE THREAD

**Issue by myuid** [nguyenq/jTessBoxEditorFX#2]
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-8u362-ga-0ubuntu1~22.04-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)

java -Xms128m -Xmx1024m -jar jTessBoxEditorFX.jar

**Comment by nguyenq** [comment]
You would need JavaFX library to launch the JavaFX-based program. If no success, you can try the Swing-based version.

https://github.com/nguyenq/jTessBoxEditor

**Comment by nguyenq** [comment]
@myuid Did you ever resolve the issue? Can you try with Java 21 & JavaFX 21?

```
export PATH_TO_FX=path/to/javafx-sdk-21.0.1/lib
java -Xms128m -Xmx1024m --module-path $PATH_TO_FX --add-modules javafx.controls,javafx.fxml,javafx.web -jar jTessBoxEditorFX.jar
```
