### ISSUE TITLE
Image not displayed

### ISSUE THREAD

**Issue by gabrielxvx** [nguyenq/jTessBoxEditorFX#3]
<img width="860" alt="Snipaste_2024-09-07_15-01-57" src="https://github.com/user-attachments/assets/9424f28f-2c39-4f8a-a48d-68fa1814d8f7">

**Comment by gabrielxvx** [comment]
java version "21.0.4" 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 21.0.4+8-LTS-274)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.4+8-LTS-274, mixed mode, sharing)

**Comment by nguyenq** [comment]
It's missing a module. Please try:

`java -Xms128m -Xmx1024m --module-path "C:\Program Files\Java\javafx-sdk-21.0.1\lib" --add-modules javafx.controls,javafx.fxml,javafx.web,javafx.swing -jar jTessBoxEditorFX.jar`
